# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"in_notebook": "00_core.ipynb",
         "ipython_info": "00_core.ipynb",
         "load_and_cache_raw_data": "01_datapipe.ipynb",
         "DATA_INFO": "88_app_st.ipynb",
         "AUTHOR_INFO": "88_app_st.ipynb",
         "APP_NAME": "88_app_st.ipynb",
         "placeholder": "88_app_st.ipynb",
         "SideBar": "88_app_st.ipynb",
         "app_sidebar": "88_app_st.ipynb",
         "app_mainscreen": "88_app_st.ipynb",
         "notebook_mainscreen": "88_app_st.ipynb",
         "sb": "88_app_st.ipynb"}

modules = ["core.py",
           "datapipe.py",
           "app_st.py"]

doc_url = "https://mjboothaus.github.io/jobkeep/"

git_url = "https://github.com/mjboothaus/jobkeep/tree/master/"

def custom_doc_links(name): return None
