# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/88_app_st.ipynb (unless otherwise specified).

__all__ = ['SideBar', 'app_sidebar', 'app_mainscreen', 'notebook_mainscreen', 'sb']

# Cell
import numpy as np
import pandas as pd
import datetime as dt
import streamlit as st
from streamlit_folium import folium_static
import folium
from PIL import Image
from IPython.display import display
#import os, io
#from dateutil.parser import parse

from .core import in_notebook
from .datapipe import load_and_cache_raw_data

# Internal Cell

DATA_INFO = '[JobKeeper: treasury.gov.au](https://treasury.gov.au/coronavirus/jobkeeper/data)'
AUTHOR_INFO = 'AUTHOR: [Michael J. Booth](https://about.me/mjboothaus)'
APP_NAME = 'JobKeep App'

st.beta_set_page_config(page_title=APP_NAME)

# Cell
class SideBar:
    datasource = DATA_INFO
    datasize = 0   # look to calculate this (in MB?) - TEST: Comment change
    author = AUTHOR_INFO
    data_title = 'Data details...'
    data_local = False
    start_date = dt.date.today()
    end_date = dt.date.today()
    selected_data = None


def app_sidebar(APP_NAME):
    IMAGE_PATH = '/Users/mjboothaus/iCloud/Code/Github/jobkeep/resources'
    sb = SideBar()

    #aw_image = Image.open(IMAGE_PATH + 'TODO.jpeg')
    #st.sidebar.image(image=aw_image, use_column_width=True, output_format='JPEG')

    st.sidebar.info(APP_NAME)
    st.sidebar.markdown(sb.author)
    st.sidebar.markdown(sb.datasource)
    st.sidebar.info(sb.data_title)
    #st.sidebar.markdown('Datasize: ' + str(sb.datasize))

    # TODO: Add custom app-specific sidebar properties/widgets

    return sb

# Cell
def app_mainscreen(APP_NAME, sb):

    st.header(APP_NAME)

    df = load_and_cache_raw_data()

    st.write(df)

    # Load data
    # TODO:

    # Create mainscreen

    return None

# Cell
def notebook_mainscreen(APP_NAME, sb):

    print(APP_NAME)

    st.header(APP_NAME)

    # Load data
    # TODO:

    # Create mainscreen

    return None

# Cell

sb = app_sidebar(APP_NAME)

if in_notebook():
    notebook_mainscreen(APP_NAME, sb)
else:
    app_mainscreen(APP_NAME, sb)