# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_datapipe.ipynb (unless otherwise specified).

__all__ = ['load_and_cache_raw_data']

# Internal Cell
import os
import pandas as pd
import activityio as aio
from dateutil.parser import parse
import datetime as dt

# Cell

# TODO: use st.cache() and also look to pre-load and cache/feather data (or similar) - NB: use of @st.cache() below didn't work
def load_and_cache_raw_data():
    DATA_PATH = '/Users/mjboothaus/iCloud/Code/Github/jobkeep/data'
    return None