# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_geog.ipynb (unless otherwise specified).

__all__ = ['extract_postcode', 'load_suburb_data']

# Cell
def extract_postcode(pc):
    try:
        postcode = np.int(pc[-4:])
    except:
        postcode = np.NaN
    return postcode

# Cell
def load_suburb_data(state_name='NSW'):
    MAP_DATA_PATH = '../data/datasets/geo-data/'
    STATE_SUBURBS_FILE = 'NSW_Suburbs.geojson.json'
    suburbs_df = gpd.read_file(MAP_DATA_PATH + STATE_SUBURBS_FILE.replace('NSW', state_name))
    suburbs_df['postcode'] = suburbs_df['loc_pid'].apply(lambda pc: extract_postcode(pc))
    suburbs_df['postcode'] = suburbs_df['postcode'].astype(np.int64, errors='ignore')
    suburbs_df.to_excel(MAP_DATA_PATH + STATE_SUBURBS_FILE.replace('NSW', state_name).replace('.geojson.json', '.xlsx'))
    return suburbs_df